openapi: 3.0.0
info:
  title: Student
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:8080'
paths:
  /student:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
      operationId: getAllStudents
      description: Gib alle Student-Objekte zurück
    post:
      summary: ''
      operationId: createStudent
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
      description: Erstelle Studenten-Objekt
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
        description: Student-Objekt
  '/student/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
      operationId: getStudentById
      description: Erhalte ein einzelnes Student-Objekt nach der Id
      parameters:
        - schema:
            type: string
          in: query
          name: id
components:
  schemas:
    Student:
      type: object
      description: Beschreibung eines Studenten
      x-examples:
        example-1:
          id: 1
          firstName: Thomas
          lastName: Tester
          studentNumber: '4711'
      title: Student
      properties:
        id:
          type: integer
          format: int64
          description: Identifer eines Student-Objekts
        firstName:
          type: string
        lastName:
          type: string
        studentNumber:
          type: string
      required:
        - id
        - firstName
        - lastName
        - studentNumber
