INSERT INTO course VALUES (1, 'Verteilte Systeme');
INSERT INTO course VALUES (2, 'Web-Programmierung');

INSERT INTO student VALUES (1, 'Tim', 'Tester', 1234);
INSERT INTO student VALUES (2, 'Peter', 'Prüfer', 5678);

INSERT INTO COURSE_ENROLLEMENT ( COURSE_ID , STUDENT_ID ) VALUES (1,2);
INSERT INTO COURSE_ENROLLEMENT ( COURSE_ID , STUDENT_ID ) VALUES (2,2);
INSERT INTO COURSE_ENROLLEMENT ( COURSE_ID , STUDENT_ID ) VALUES (1,1);

-- INSERT INTO STUDENT_COURSE_LIST ( COURSE_LIST_ID , ENROLLED_STUDENTS_ID ) VALUES (1,2);